pipeline {
  agent any
  stages {
    stage ('Initialize') {
      steps {
        echo 'Placeholder.'
      }
    }
    stage('Deliver') {
      steps {
          sh './jenkins/scripts/deliver.sh'
      }
    }    
  }
}