pipeline {
  agent any
  stages {
    stage ('Initialize') {
      steps {
        echo 'Placeholder.'
      }
    }
    stage('Build') {
      steps {
          // sh 'mvn -DskipTests clean install'
      }
    }
    stage('Build') {
      steps {
          sh './jenkins/scripts/deliver.sh'
      }
    }
    
  }
}